### ISSUE TITLE
Manual input date does not trigger on change when close on select is true

### ISSUE THREAD

**Issue by ryanzeroseven** [Itvisors/mendix-ReactDateTimePicker#13] opened 2023-10-12 10:55 UTC
After a date is selected and user manually removes and types in a new date the on change is not triggered and the calendar pop up closes. This causes wrong data to be used. For instance if the date selected from the calendar is 13th of October and afterwards the user empties the field with keyboard and types a different date, the new date is not triggering any event and for example on a sent button the button for a form the attribute is not updated with the new date input. 
Comparing the code from the widget in Mendix Marketplace and doing a npm install building the widget itself it seems in the react-datetime lib there is a line in DateTime.js line 158 that is different from yours. the .js file when unzipping the mpk is where i found the difference. Not sure if you customized the lib and shipped the widget to the marketplace or this was newly added in the lib.

**Comment by jeuhen** [comment] 2023-10-16 08:28
Hi, Thanks for your feedback. I just tested this in the demo project (in the test folder), but was not able to reproduce in the CloseOnSelect page. Also the calendar popup does not close while typing in my scenario. Are you sure that the user filled a valid date and that you also validate this(with the valid date property)?
Can you also reprocuce this in the demo project? On which version of Mendix are you running and did you download the latest version of the widget?

**Comment by ryanzeroseven** [comment] 2023-10-16 08:56
Hi! Thank you for replying. Sorry I should have been more clear. I was trying to extend your widget and add more functionality to it. When downloading your .zip and building the widget with out any new changes just installing the node modules and building it, the issue is there that on input and typing the calendar disappears. 
I would expect it to work the same as the widget from the Marketplace only difference would be that the build happened on my machine. When comparing code I noticed differences in the react-datetime library. When aligning the changes (copying your .js and adding it to my widget's react-datetime library), the widget works the same as the one in the marketplace and in your demo. So I wonder if you installed something more or did you make changes to the library before shipping it to the Marketplace? I hope this is a bit more clear, I'm not sure how to better explain this. Maybe I'm missing some extension or installation.
Again thank you for the quick reply!

**Comment by jeuhen** [comment] 2023-10-16 09:42
I indeed made some changes to the library to allow for week numbers, but I have to check if this also impacts this part. I guess you use the same version of the library that I used?
What do you want to extend to the widget? I guess you made a pull request for this?

**Comment by ryanzeroseven** [comment] 2023-10-16 10:55
Well, this is kind of new for me so I was just playing around to see if I could build a widget and extend. I wanted a boolean to disable weekends, sundays and holidays (from an array) and those work fine, also instead of an attribute I wanted to use expressions for min and max dates. Functionally it works except for the issue with the on change not working on manual input. 
What I did was just an npm install, so I assume the library is the same then...I did see changes in your version of the library in the ReactDAteTimePicker.js for tabIndex and showWeekNumbers when unzipping the mpk after building. 
As mentioned before I was playing around on my my machine only so I haven't done a pull request, not sure how that works either. I'm just trying to learn and see what I can make of it. My apologies in advance if I did something not okay.

**Comment by jeuhen** [comment] 2024-01-10 15:47
Sorry for the late response. I indeed made some changes to the library that were not possible by default. 
Of course you can play with the widget and add anything you like. The advantage of making a pull request is that, once I merged the changes is that other people can also use your additions and perhaps give feedback on it/improve it further and you can still upgrade the widget when there are new updates. 
I hope you already found a solution or do you still have an issue?

**Closed as not planned** 2024-02-15 08:09 UTC
