### ISSUE TITLE
Locale is reset after OnChange event

### ISSUE THREAD

**Issue by RuudFl** [Itvisors/mendix-ReactDateTimePicker#11] opened 2022-10-12 15:16 UTC
After an onchange event, the locale is reset, and the default locale is visible

**Comment by jeuhen** [comment] 2022-10-12 15:24
Hi Ruud,

Can you share a bit more information/screenshots?
Are you using the lastest version of the widget?
I just tried, but cannot reproduce.

Kind regards,

Johan

**Comment by RuudFl** [comment] 2022-10-13 13:24
> Hi Ruud,
> 
> Can you share a bit more information/screenshots? Are you using the lastest version of the widget? I just tried, but cannot reproduce.
> 
> Kind regards,
> 
> Johan

Hi Johan, have a look [here](https://www.loom.com/share/cc0510f5cff04cd7b120e7244909bc5c)

**Comment by jeuhen** [comment] 2023-06-23 07:02
This issue is fixed in a past release, forgot to close until now

**Closed as completed by jeuhen** 2023-06-23 07:02 UTC
